"""Initial migration

Revision ID: feb18c284840
Revises: 1516e6904271
Create Date: 2025-09-18 23:04:46.227325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb18c284840'
down_revision = '1516e6904271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('typedoc', sa.String(length=50), nullable=False),
    sa.Column('datedepot', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('dategeneration', sa.DateTime(), nullable=True),
    sa.Column('idmanager', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idmanager'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('droits_acces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typedroit', sa.String(length=20), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('iddoc', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iddoc'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iduser', 'iddoc', 'typedroit', name='unique_droit_user_doc')
    )
    op.create_table('journaux_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('dateaction', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('iddoc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iddoc'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iddoc', sa.Integer(), nullable=False),
    sa.Column('idmanager', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('datevalidation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iddoc'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['idmanager'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iddoc', 'idmanager', name='unique_validation_doc_manager')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_table('journaux_activite')
    op.drop_table('droits_acces')
    op.drop_table('rapports')
    op.drop_table('documents')
    # ### end Alembic commands ###
